# Generated by Django 6.0.2 on 2026-05-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_adoption_foundation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dog',
            new_name='dogs_dog_adoptio_7a4e18_idx',
            old_name='dogs_dog_adoptio_739fc8_idx',
        ),
        migrations.RenameIndex(
            model_name='dog',
            new_name='dogs_dog_source__e8e268_idx',
            old_name='dogs_dog_source__c0e2e0_idx',
        ),
    ]
