# Generated by Django 6.0.2 on 2026-05-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_preferred_contact_method_choices'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contactsubmission',
            new_name='contact_con_status_b337da_idx',
            old_name='contact_con_status_4168ae_idx',
        ),
        migrations.RenameIndex(
            model_name='contactsubmission',
            new_name='contact_con_country_dbc95c_idx',
            old_name='contact_con_country_f88bdb_idx',
        ),
    ]
